namespace AAClib
{
    public enum ActivityTypes
    {
        None,
        Reading,
        Writing,
        Processing,
        Error
    }

    public delegate void ReportProgressHandler(ActivityTypes activity, long currentpos, string message);
    public delegate void ProcessingHandler(long currentpos);

    /// <summary>
    /// This exists purely to fire off events which can be generated by all objects.  The Utilities module will own one of these and MP4
    /// Reader will point to same instance and pick up the events.
    /// </summary>
    public class ReporterEngine
    {
        public event ReportProgressHandler SendReport;
        public event ProcessingHandler Processing;

        public void DoSendReport(ActivityTypes activity, long seekpos, string message)
        {
            SendReport(activity, seekpos, message);
        }

        public void DoProcessing(long currentpos)
        {
            Processing(currentpos);
        }
    }
}
